services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    ports:
      - 8089:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data/
    restart: unless-stopped
    command:
      - "start-dev"

volumes:
  keycloak_data: